base_url = "https://my.cmems-du.eu/motu-web/Motu"
input_filename = "api_parameters.csv"
output_filename = "result.nc"
dataset_id = "cmems_mod_glo_phy_my_0.083deg_P1D-m"
variables = ["thetao", "zos"]
period = [2012, 2020]
distance = "euclidean"
