base_url = "https://my.cmems-du.eu/motu-web/Motu"
input_filename = "api_parameters.csv"
output_filename = "result.nc"
dataset_id = "cmems_mod_glo_phy-thetao_anfc_0.083deg_P1D-m"
variables = ["thetao"]
years = [2021, 2022]
distance = "euclidean"
start_mode = 2  # 0 start afresh, 1 resume from given years interval and 2 read only from disk
