base_url = "https://my.cmems-du.eu/motu-web/Motu"
input_filename = "api_parameters.csv"
output_filename = "result.nc"
dataset_id = "cmems_mod_glo_phy_my_0.083deg_P1M-m"
variables = ["thetao", "zos"]
years = [2015, 2020]
distance = "euclidean"
start_mode = 1  # 0 start afresh, 1 resume
